- package: "@zowe/zos"
  registry: https://registry.npmjs.org/
  version: 0.0.1
  priority: 1
  listeners:
    - ZosMessageListener
    - ZosEventListener
- package: "@zowe/clicmd"
  registry: https://registry.npmjs.org/
  version: 0.0.1
  priority: 2
  listeners:
    - ZoweCliCommandMessageListener
    - ZoweCliCommandEventListener
