# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Zowe CLI

on:
  push:
    paths-ignore:
      - zowex/**
  pull_request:
    paths-ignore:
      - zowex/**
  workflow_dispatch:
    inputs:
      binary-type:
        description: Specify whether to use a `debug` or a `release` version of the binary
        default: debug
        required: false
      test-type:
        description: Specify whether to run tests using the `binary` or regular `nodejs` executable
        default: binary
        required: false
#   TODO: convert imperative-branch to commonbot branch once its moved to another repo?
#      imperative-branch:
#        description: Specify name of Imperative branch to checkout and build from source
#        required: false

jobs:
  test:
    name: Cross-Platform Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x, 18.x]
        os: [windows-latest, ubuntu-latest, macos-latest]

    env:
      OS: ${{ matrix.os }}
      NODE: ${{ matrix.node-version }}
      NODE_OPTIONS: --max_old_space_size=4096

    timeout-minutes: 60

    concurrency:
      group: ${{ matrix.os }}-node-${{ matrix.node-version }}-ci-${{ github.ref }}
      cancel-in-progress: true

    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) && !contains(github.event.head_commit.message, '[ci skip]')
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Get NPM Version
      id: npm-version
      run: echo "::set-output name=number::$(npm --version)"

    - name: Use NPM v8
      id: npm8
      run: npm install -g npm@~8.3.2

    - name: Install Node Package Dependencies
      id: install
      run: npm ci

    - name: Use Original NPM Version
      id: original-npm-version
      run: npm install -g npm@${{ steps.npm-version.outputs.number }}

# // TODO: repurpose for commonbot once that has its own repo
 #  - name: Checkout Imperative
 #    id: checkout-imperative
 #    if: github.event_name == 'workflow_dispatch' && github.event.inputs.imperative-branch != ''
 #    run: |
 #      cd node_modules/@zowe && npx rimraf imperative
 #      git clone --branch ${{ github.event.inputs.imperative-branch }} --depth 1 https://github.com/zowe/imperative.git
 #      cd imperative && npm ci --ignore-scripts && npx tsc

    - name: Build Source
      id: build
      run: npm run buildAll --if-present

    - name: Build Binary
      id: build-binary
      if: github.event.inputs.test-type == 'binary' || github.event_name == 'push'
      run: |
        cargo build --verbose ${{ github.event.inputs.binary-type == 'release' && '--release' || '' }} --manifest-path=zowex/Cargo.toml
        tar -cvzf zowe.tgz -C zowex/target/${{ github.event.inputs.binary-type == 'release' && 'release' || 'debug' }} zowe${{ matrix.os == 'windows-latest' && '.exe' || '' }}

    - name: Archive Binary
      if: github.event.inputs.test-type == 'binary' || github.event_name == 'push'
      id: upload-binary
      uses: actions/upload-artifact@v2
      with:
        name: zowe-${{ matrix.os }}.tgz
        path: zowe.tgz

    - name: Setup Binary in PATH
      if: github.event.inputs.test-type == 'binary' || github.event_name == 'push'
      id: setup-binary
      shell: bash
      run: |
        tar -xvzf zowe.tgz -C ./__tests__/__resources__/daemon_instances
        echo "${{ github.workspace }}/__tests__/__resources__/application_instances" >> $GITHUB_PATH

    - name: Test Rust EXE and zowe script
      id: test-exe-and-script
      if: ${{ steps.setup-binary.outcome == 'success' && (github.event.inputs.test-type == 'binary' || github.event_name == 'push') }}
      run: cargo test ${{ github.event.inputs.binary-type == 'release' && '--release' || '' }} --manifest-path=zowex/Cargo.toml -- --nocapture

    - name: Unit Tests
      id: unit
      if: ${{ always() && steps.build.outcome == 'success' }}
      run: npm run test:unit

    - name: Unlock Keyring
      id: unlock-keyring
      if: ${{ always() && steps.build.outcome == 'success' && matrix.os == 'ubuntu-latest' }}
      uses: t1m0thyj/unlock-keyring@v1

    - name: Start Daemon on Windows only
      id: start-daemon
      if: ${{ always() && steps.build.outcome == 'success' && matrix.os == 'windows-latest' && (github.event.inputs.test-type == 'binary' || github.event_name == 'push') }}
      run: ./__tests__/__resources__/daemon_instances/zowe

    - name: Integration Tests (Native)
      id: integration-native
      if: ${{ always() && steps.build.outcome == 'success' && !(github.event.inputs.test-type == 'binary' || github.event_name == 'push') }}
      run: npm run test:integration

    - name: Integration Tests (Daemon)
      id: integration-daemon
      if: ${{ always() && steps.build.outcome == 'success' && (github.event.inputs.test-type == 'binary' || github.event_name == 'push') }}
      run: npm run test:integration -- --runInBand

    - name: Archive Results
      id: upload
      if: ${{ always() && steps.build.outcome == 'success' }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-${{ matrix.node-version }}-results
        path: __tests__/__results__/

    - name: Upload Results to Codecov
      id: upload-codecov
      if: ${{ always() && steps.build.outcome == 'success' }}
      uses: codecov/codecov-action@v3
      with:
        env_vars: OS,NODE
